#!/usr/bin/perl -w

use strict;

# Windows users will have to change the following line from
# $ENV{'HOME'} to $ENV{'APPDATA'}
# in order to take advantage of having 'personal' providers and receivers
# files.
my $homecfg = $ENV{'HOME'};

my $datain = '';
my %receivers = ();
my %providers = ();

sub GetReceivers {
	# GetReceivers() Params
	# $FilePath = Path to file containing receivers
	# #DieOnFail = Should the program die if it can't open the file?
	
	my ($FilePath, $DieOnFail) = @_;
	my $IsOpen = '';
	my $recvdata = '';
	
	if ( $DieOnFail ) {
		$IsOpen = open(GETRECV, "$FilePath") or die("Unable to open [$FilePath]\n");
	} else {
		$IsOpen = open(GETRECV, "$FilePath");
	}	
	if ( !$IsOpen ) { return 0; }
	$recvdata = readline GETRECV;
	if ( !$recvdata ) { return 0; }
	while ( $recvdata ) {
		my ($name, $provider, $number) = split(' ', "\L$recvdata\E");
		if ( !exists $receivers{"$name"} ) {
			$receivers{"$name"}[0] = $provider;
			$receivers{"$name"}[1] = $number;
		}
		$recvdata = readline GETRECV;
	}
}

sub GetProviders {
	# GetProviders() Params
	# $FilePath = Path to file containing providers
	# #DieOnFail = Should the program die if it can't open the file?
	
	my ($FilePath, $DieOnFail) = @_;
	my $IsOpen = '';
	my $recvdata = '';
	
	if ( $DieOnFail ) {
		$IsOpen = open(GETPROV, "$FilePath") or die("Unable to open [$FilePath]\n");
	} else {
		$IsOpen = open(GETPROV, "$FilePath");
	}	
	if ( !$IsOpen ) { return 0; }
	$recvdata = readline GETPROV;
	if ( !$recvdata ) { return 0; }
	while ( $recvdata ) {
		my ($name, $address, $port, $maxchars) = split(' ', "\L$recvdata\E");
		if ( !exists $providers{"$name"} ) {
			$providers{"$name"}[0] = $address;
			$providers{"$name"}[1] = $port;
			$providers{"$name"}[2] = $maxchars;
		}
		$recvdata = readline GETPROV;
	}
}

GetReceivers("$homecfg/.snppsend/receivers", 0);
GetReceivers("/etc/snppsend/receivers", 0);
GetProviders("$homecfg/.snppsend/providers",0);
GetProviders("/etc/snppsend/providers",0);

# dosomedebug();

sub dosomedebug {
	foreach ( keys %receivers ) {
		print "RECV: ", $_, " [", $receivers{$_}[1], "]\n";
	}

	foreach ( keys %providers ) {
		print "PROV: ", $_, " [", $providers{$_}[0], "]\n";
	}
}
